### ISSUE TITLE
middle click also removes download from history 

### ISSUE THREAD

**Issue by GiftWolf** [Infocatcher/Download_Panel_Tweaker#39]
I have the "Also remove from history" feature disabled. However when I middle click the download is also removed from history.

**Comment by Infocatcher** [comment]
Oops, something was changed in recent Firefox version. I'll take a look.

With _extensions.downloadPanelTweaker.debug_ = true in error/browser console:
```
[Download Panel Tweaker] 49:58:642 removeFromPanel(): dlController.dataItem.remove() not available!
[Download Panel Tweaker] 49:58:646 removeFromPanel() -> dlController.doCommand("cmd_delete")
```

**Comment by Infocatcher** [comment]
Now looks fixed for me.
Test version: <a href="http://infocatcher.ucoz.net/temp/dpt/download_panel_tweaker-0.2.5pre-fx.xpi">download_panel_tweaker-0.2.5pre-fx.xpi</a> (<a href="https://github.com/Infocatcher/Download_Panel_Tweaker/tree/a8c5915c287a581c7c78b5d8902b250f104100d7">source code</a>).

**Comment by Infocatcher** [comment]
https://addons.mozilla.org/firefox/addon/download-panel-tweaker/versions/0.2.5
