### ISSUE TITLE
New style changes in FF 52

### ISSUE THREAD

**Issue by Keith94** [Infocatcher/Download_Panel_Tweaker#48]
In FF 52 the download panel was recently updated, so the Compact and Very compact styles have multiple issues and may need updating to look more "compact" again.

Compact:
![2016-10-17_06-36-58](https://cloud.githubusercontent.com/assets/5490615/19439797/54c2153c-9434-11e6-8f14-217c28ed9513.png)

Very compact:
![2016-10-17_06-37-01](https://cloud.githubusercontent.com/assets/5490615/19439806/5a64ec26-9434-11e6-9717-7db8fe97dad5.png)

**Comment by Infocatcher** [comment]
Oh, yes... Also footer (Show All Downloads & Co) was changed too, in Firefox 50+.

Test version: <a href="http://infocatcher.ucoz.net/temp/dpt/download_panel_tweaker-0.2.6pre3-fx.xpi">download_panel_tweaker-0.2.6pre3-fx.xpi</a> (<a href="https://github.com/Infocatcher/Download_Panel_Tweaker/tree/5de7c0cee59e65bbcf7ce2e0ae1dd5c399295346">source code</a>)

**Comment by Keith94** [comment]
Looking good! Thanks :)

**Comment by Keith94** [comment]
Hmm, I noticed the panel height increases in some cases, is that related to this issue?

STR:

1. Download about 4-5 files
2. Open dropmarker (in the footer) and choose "Clear Preview Panel"
3. Open dropmarker again, which causes the panel height to increase

![firefox_2016-10-19_01-29-35](https://cloud.githubusercontent.com/assets/5490615/19511648/ecab16f0-959c-11e6-9634-dd4c32c94725.png)

**Comment by Infocatcher** [comment]
> Open dropmarker again, which causes the panel height to increase

I see...
This is something related to reason of following fixes: f00d6534efb6366bef668ec10756da77953922d2, 306eb8d53bda6228ef5e31d86290a8909bcf84eb, b8f44d72f875db2a4eb9012616072cd039ea711b
Not caused by "compact" styles, but may comes from changed "Visible downloads count limit".

**Comment by Infocatcher** [comment]
Yet another trick: c25a1cbf046640f1fa5e343a6377c2806b7bed8f

Test version: <a href="http://infocatcher.ucoz.net/temp/dpt/download_panel_tweaker-0.2.6pre4-fx.xpi">download_panel_tweaker-0.2.6pre4-fx.xpi</a> (<a href="https://github.com/Infocatcher/Download_Panel_Tweaker/tree/c25a1cbf046640f1fa5e343a6377c2806b7bed8f">source code</a>)

**Comment by Keith94** [comment]
OK, this latest one works fine for me. Closing..

**Comment by Infocatcher** [comment]
Great. Thanks for testing.
