### ISSUE TITLE
Add "Clear Downloads" command to footer dropmarker

### ISSUE THREAD

**Issue by Keith94** [Infocatcher/Download_Panel_Tweaker#50]
Add "Clear Downloads" here as well maybe?

![firefox_2016-10-20_13-01-34](https://cloud.githubusercontent.com/assets/5490615/19575848/6d21d354-96c5-11e6-9df4-55d94f502c56.png)

**Comment by Infocatcher** [comment]
Added, see test version here: https://github.com/Infocatcher/Download_Panel_Tweaker/issues/49#issuecomment-255447933

**Comment by Keith94** [comment]
Works well, however when there are no more downloads in panel, you should hide the "Clear Downloads".

Also right-clicking the footer currently shows the menu item, is that right?

**Comment by Infocatcher** [comment]
> when there are no more downloads in panel, you should hide the "Clear Downloads".

This is not only about panel: it's possible to clear downloads history even if panel is empty (also will be cleared Library - Downloads)

> Also right-clicking the footer currently shows the menu item, is that right?

This is old feature to clear downloads in case of empty panel (with not available context menu for download entries).

**Comment by Infocatcher** [comment]
Unfortunately I'm not see trivial way to detect, if there is something to remove from downloads history.
Only hardcore tricks like
```js
PlacesUtils.history.DBConnection.createStatement("SELECT … FROM moz_places WHERE …")
```

**Comment by Keith94** [comment]
I see, thanks for the clarification. I guess it's working as intended. :)
